#include <stdio.h>
#include <stdlib.h>

int main()
    {
          printf("HAHAHA");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");
          system("cd..");
          system("dir");
          system("cd..");
          system("dir");
          system("cd Pablo");
          system("cd C");
          system("dir");

          
          system("pause");
          return 0;
          
          }
